[package]
name = "vesper-boot"

description = "Vesper nanokernel boot PIE section."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]
aarch64-cpu = { workspace = true }
libcpu = { workspace = true }
libplatform = { workspace = true }
tock-registers = { workspace = true }

# Tests are offloaded to kernel integration tests binary.
[lib]
test = false
harness = false

[lints]
workspace = true
