[package]
name = "libsyscall"

description = "Syscall interface"

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]

# Tests are offloaded to kernel integration tests binary.
[lib]
test = false

[lints]
workspace = true
