[workspace]
members = [
  "machine",
  "nucleus",
  "bin/chainboot",
  "bin/chainofcommand",
  # Libraries
  "libs/console",
  "libs/cpu",
  "libs/exception",
  "libs/kernel-state",
  "libs/local-irq",
  "libs/locking",
  "libs/log",
  "libs/memory",
  "libs/platform",
  "libs/primitives",
  "libs/qemu",
  "libs/test",
  "libs/time",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Berkus Decker <berkus+vesper@metta.systems>"]
documentation = "https://docs.metta.systems/vesper"
homepage = "https://github.com/metta-systems/vesper"
repository = "https://github.com/metta-systems/vesper"
readme = "README.md"
license = "BlueOak-1.0.0"
categories = ["no-std", "embedded", "os"]
publish = false
edition = "2024"

[workspace.dependencies]
aarch64-cpu = { version = "10.0" }
bit_field = "0.10"
bitflags = "2.9"
buddy-alloc = { git = "https://github.com/metta-systems/buddy-alloc", version = "0.6.0", branch = "feature/allocator-api" }
cfg-if = "1.0"
libconsole = { path = "libs/console" }
libcpu = { path = "libs/cpu" }
libexception = { path = "libs/exception" }
libkernel-state = { path = "libs/kernel-state" }
liblocal-irq = { path = "libs/local-irq" }
liblocking = { path = "libs/locking" }
liblog = { path = "libs/log" }
libmemory = { path = "libs/memory" }
libplatform = { path = "libs/platform" }
libprimitives = { path = "libs/primitives" }
libqemu = { path = "libs/qemu" }
libtest = { path = "libs/test" }
libtime = { path = "libs/time" }
once_cell = { version = "1.21", default-features = false, features = [
  "unstable",
] }
qemu-exit = "3.0"
seahash = "4.1"
snafu = { version = "0.8", default-features = false, features = [
  "unstable-core-error",
] }
tock-registers = "0.9"
usize_conversions = "0.2"
ux = { version = "0.1", default-features = false }

[patch.crates-io]
serialport = { git = "https://github.com/metta-systems/serialport-rs", branch = "macos-ENOTTY-fix" }

[profile.dev]
# See https://github.com/rust-lang/cargo/issues/7359 about why panic=abort is not working here.
# It is still defined in the target JSON so not stricly necessary to specify it here anyway.
#panic = "abort" # @todo try panic_rtt with feature jlink
opt-level = 's' # otherwise boot code will be mangled

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 's'
panic = "abort"

[profile.release-fast]
codegen-units = 16
inherits = "release"
lto = "thin"

[profile.test]
debug = true
opt-level = 's'

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(board_rpi3)', 'cfg(board_rpi4)'] }
