[workspace]
members = [
  "nucleus",
  "bin/chainboot",
  "bin/chainofcommand",
  # Libraries
  "libs/console",
  "libs/cpu",
  "libs/exception",
  "libs/kernel-state",
  "libs/local-irq",
  "libs/locking",
  "libs/log",
  "libs/machine",
  "libs/memory",
  "libs/platform",
  "libs/primitives",
  "libs/qemu",
  "libs/test",
  "libs/time",
]
resolver = "2"

[workspace.package]
authors = ["Berkus Decker <berkus+vesper@metta.systems>"]
categories = ["embedded", "no-std", "os"]
documentation = "https://docs.metta.systems/vesper"
edition = "2024"
homepage = "https://github.com/metta-systems/vesper"
license = "BlueOak-1.0.0"
publish = false
readme = "README.md"
repository = "https://github.com/metta-systems/vesper"
version = "0.0.1"

[workspace.dependencies]
#========
# target
#========
aarch64-cpu = { version = "10.0" }
bit_field = { version = "0.10" }
bitflags = { version = "2.9" }
buddy-alloc = { version = "0.6.0", git = "https://github.com/metta-systems/buddy-alloc", branch = "feature/allocator-api" }
cfg-if = { version = "1.0" }
libconsole = { path = "libs/console" }
libcpu = { path = "libs/cpu" }
libexception = { path = "libs/exception" }
libkernel-state = { path = "libs/kernel-state" }
liblocal-irq = { path = "libs/local-irq" }
liblocking = { path = "libs/locking" }
liblog = { path = "libs/log" }
libmachine = { path = "libs/machine" }
libmemory = { path = "libs/memory" }
libplatform = { path = "libs/platform" }
libprimitives = { path = "libs/primitives" }
libqemu = { path = "libs/qemu" }
libtest = { path = "libs/test" }
libtime = { path = "libs/time" }
once_cell = { version = "1.21", default-features = false, features = ["unstable"] }
qemu-exit = { version = "3.0" }
snafu = { version = "0.8", default-features = false, features = ["unstable-core-error"] }
tock-registers = { version = "0.9" }
usize_conversions = { version = "0.2" }
ux = { version = "0.1", default-features = false }
#======
# host
#======
anyhow = { version = "1.0" }
argh = { version = "0.1" }
bytes = { version = "1.10" }
crossterm = { version = "0.29", features = ["event-stream"] }
defer = { version = "0.2" }
futures = { version = "0.3" }
futures-util = { version = "0.3", features = ["io"] }
tokio = { version = "1.47", features = ["full"] }
tokio-serial = { version = "5.4" }
tokio-stream = { version = "0.1" }
tokio-util = { version = "0.7", features = ["codec", "io"] }
#=======
# mixed
#=======
seahash = { version = "4.1" }

[patch.crates-io]
serialport = { git = "https://github.com/metta-systems/serialport-rs", branch = "macos-ENOTTY-fix" }

[profile.dev]
# See https://github.com/rust-lang/cargo/issues/7359 about why panic=abort is not working here.
# It is still defined in the target JSON so not stricly necessary to specify it here anyway.
#panic = "abort" # @todo try panic_rtt with feature jlink
opt-level = 's' # otherwise boot code will be mangled

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 's'
panic = "abort"

[profile.release-fast]
codegen-units = 16
inherits = "release"
lto = "thin"

[profile.test]
debug = true
opt-level = 's'

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(board_rpi3)', 'cfg(board_rpi4)'] }
