tag_prefix = "R"
ignore_merge_commits = true

[commit_types]
wip = { changelog_title = "Work in progress (should not be in changelog!)" }
sq = { changelog_title = "Should be squashed with other commit (should not be in changelog!)" }
