// Auto-generated kernel section metadata and binary includes
// DO NOT EDIT - Generated by build.rs

#[allow(unused)]
use libimage::{
    KernelImage, LoadableSection, Permissions, SectionMeta,
};

// ═══════════════════════════════════════════════════════════════
// Binary section data (included at compile time)
// ═══════════════════════════════════════════════════════════════

{% for section in sections %}
static {{section.bin_name}}: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/{{section.bin_file}}"));
{% endfor %}

// ═══════════════════════════════════════════════════════════════
// Section metadata
// ═══════════════════════════════════════════════════════════════

{% for section in sections %}
pub const {{section.meta_name}}: SectionMeta = SectionMeta {
    name: "{{section.name}}",
    virt_addr: {{section.virt_addr | address}},
    size: {{section.size | hex}},
    alignment: {{section.align | hex}},
    permissions: Permissions { readable: {{section.r|bool}}, writable: {{section.w|bool}}, executable: {{section.x|bool}} },
};
{% endfor %}

pub const BSS_META: SectionMeta = SectionMeta {
    name: ".bss",
    virt_addr: {{bss.virt_addr | address}},
    size: {{bss.size | hex}},
    alignment: {{bss.align | hex}},
    permissions: Permissions { readable: true, writable: true, executable: false },
};

// ═══════════════════════════════════════════════════════════════
// Exception vector table
// ═══════════════════════════════════════════════════════════════

pub const VECTORS_META: SectionMeta = SectionMeta {
    name: ".vectors",
    virt_addr: {{vectors.virt_addr | address}},
    size: {{vectors.size | hex}},
    alignment: {{vectors.align | hex}},
    permissions: Permissions { readable: true, writable: false, executable: true },
};

/// Exported setter that records the boot-carved Nucleus address.
pub const NUCLEUS_SET_ANCHOR_VIRT: u64 = {{nucleus_set_anchor_virt | address}};

/// Exported boot-only installer of the privileged interrupt-controller component.
pub const NUCLEUS_SET_PLATFORM_VIRT: u64 = {{nucleus_set_platform_virt | address}};

// ═══════════════════════════════════════════════════════════════
// Combined kernel sections
// ═══════════════════════════════════════════════════════════════

static LOADABLE_SECTIONS: &[LoadableSection] = &[
{% for section in sections %}
    LoadableSection { meta: {{section.meta_name}}, data: {{section.bin_name}} },
{% endfor %}
];

/// Complete kernel image information
pub static KERNEL: KernelImage = KernelImage {
    virt_base: {{virt_addr | address}},
    sections: LOADABLE_SECTIONS,
    bss: BSS_META,
    vectors: VECTORS_META,
    stack_virt_bottom: {{stack_virt_bottom | address}},
};
