[package]
name = "libmemory"

description = "Vesper nanokernel Memory Descriptors shared code library."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]
aarch64-cpu = { workspace = true }
libaddress = { workspace = true }
liblog = { workspace = true }
libmapping = { workspace = true }
snafu = { workspace = true }
tock-registers = { workspace = true }

[lib]
test = false

[lints]
workspace = true
