[package]
name = "vesper-print"

description = "Vesper nanokernel buffered output functions for no_std."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]

[lib]
test = false
harness = false

[lints]
workspace = true
