// Auto-generated kernel section metadata and binary includes
// DO NOT EDIT - Generated by build.rs

#[allow(unused)]
use crate::{
    loader::{ImageInfo, SectionMeta, LoadableSection},
    memory::MemoryPermissions
};

// ═══════════════════════════════════════════════════════════════
// Binary section data (included at compile time)
// ═══════════════════════════════════════════════════════════════

{% for section in sections %}
static {{section.bin_name}}: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/{{section.bin_file}}"));
{% endfor %}

// ═══════════════════════════════════════════════════════════════
// Section metadata
// ═══════════════════════════════════════════════════════════════

{% for section in sections %}
pub const {{section.meta_name}}: SectionMeta = SectionMeta {
    name: "{{section.name}}",
    virt_addr: {{section.virt_addr | address}},
    size: {{section.size | hex}},
    alignment: {{section.align | hex}},
    permissions: MemoryPermissions { readable: {{section.r}}, writable: {{section.w}}, executable: {{section.x}} },
};
{% endfor %}

pub const BSS_META: SectionMeta = SectionMeta {
    name: ".bss",
    virt_addr: {{bss.virt_addr | address}},
    size: {{bss.size | hex}},
    alignment: {{bss.align | hex}},
    permissions: MemoryPermissions { readable: true, writable: true, executable: false },
};

// ═══════════════════════════════════════════════════════════════
// Exception vector table
// ═══════════════════════════════════════════════════════════════

pub const VECTORS_META: SectionMeta = SectionMeta {
    name: ".vectors",
    virt_addr: {{vectors.virt_addr | address}},
    size: {{vectors.size | hex}},
    alignment: {{vectors.align | hex}},
    permissions: MemoryPermissions { readable: true, writable: false, executable: true },
};

// ═══════════════════════════════════════════════════════════════
// Combined kernel sections
// ═══════════════════════════════════════════════════════════════

static LOADABLE_SECTIONS: &[LoadableSection] = &[
{% for section in sections %}
    LoadableSection { meta: {{section.meta_name}}, data: {{section.bin_name}} },
{% endfor %}
];

/// Complete kernel image information
pub static KERNEL: ImageInfo = ImageInfo {
    virt_base: {{virt_addr | address}},
    sections: LOADABLE_SECTIONS,
    bss: BSS_META,
    vectors: VECTORS_META,
};
