[package]
name = "libqemu"

description = "QEMU implementations"

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]
libprint = { workspace = true }

# [dev-dependencies]
# libtest = { workspace = true }

# Tests are offloaded to kernel integration tests binary.
[lib]
test = false
harness = false

[lints]
workspace = true
