[package]
name = "liblocking"

description = "Synchronization primitives."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]
libkernel-state = { workspace = true }
liblocal-irq = { workspace = true }

[lints]
workspace = true
