[package]
name = "vesper-locking"

description = "Vesper nanokernel synchronization primitives."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]
libkernel-state = { workspace = true }
liblocal-irq = { workspace = true }

[dev-dependencies]
libboot = { workspace = true }
libconsole = { workspace = true }
liblog = { workspace = true }
libqemu = { workspace = true }
libtest = { workspace = true }

[lib]
test = false
harness = false

[lints]
workspace = true
