#
# SPDX-License-Identifier: BlueOak-1.0.0
#
# Copyright (c) Berkus Decker <berkus+vesper@metta.systems>
#
# Build ttt tool
#
[tasks.build]
clear = true
alias = "ttt"

[tasks.ttt]
clear = true
alias = "ttt-binary"

[tasks.ttt-binary]
env = { "TARGET_FEATURES" = "${TARGET_BOARD}" }
command = "cargo"
args = ["build", "--features=${TARGET_FEATURES}"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

#[tasks.build-kernel-binary] #  Invert this, kernel binary shall depend on ttt-binary availability
#dependencies = ["build"]
