#
# SPDX-License-Identifier: BlueOak-1.0.0
#
# Copyright (c) Berkus Decker <berkus+vesper@metta.systems>
#
# Build ttt tool
#
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
disabled = true
alias = "ttt-binary"

[tasks.build-device]
alias = "ttt-binary"

[tasks.ttt]
workspace = false
alias = "ttt-binary"

[tasks.ttt-binary]
workspace = false
env = { "TARGET_FEATURES" = "${TARGET_BOARD}" }
command = "cargo"
args = ["build", "--features=${TARGET_FEATURES}"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.xtool-clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

#[tasks.build-kernel-binary] #  Invert this, kernel binary shall depend on ttt-binary availability
#dependencies = ["build"]
