[package]
name = "libmmio"
description = "Vesper nanokernel MMIO abstractions."
authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
publish = false

[badges]
maintenance = { status = "experimental" }

[dependencies]
libaddress = { workspace = true }
safe-mmio = { workspace = true }

# Tests are offloaded to kernel integration tests binary.
[lib]
test = false

[lints]
workspace = true
