[package]
name = "libcpu"

description = "Vesper nanokernel CPU support."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[package.metadata.layer]
deps = []
description = ""

[badges]
maintenance = { status = "experimental" }

[dependencies]
aarch64-cpu = { workspace = true }

# Tests are offloaded to kernel integration tests binary.
[lib]
test = false
harness = false

# For proper testing in libcpu, we build it as a test_runner binary!

[lints]
workspace = true
