[package]
name = "chainofcommand"
version = "0.0.1"
authors = ["Berkus Decker <berkus+vesper@metta.systems>"]
description = "Host server for chainboot"
license = "BlueOak-1.0.0"
categories = ["no-std", "embedded", "os"]
publish = false
edition = "2021"

[badges]
maintenance = { status = "experimental" }

[dependencies]
clap = "4.4"
seahash = "4.1"
anyhow = "1.0"
fehler = "1.0"
crossterm = { version = "0.27", features = ["event-stream"] }
futures = "0.3"
futures-util = { version = "0.3", features = ["io"] }
tokio = { version = "1.33", features = ["full"] }
tokio-util = { version = "0.7", features = ["io", "codec", "io"] }
tokio-stream = { version = "0.1" }
tokio-serial = "5.4"
defer = "0.2"
bytes = "1.5"
