[package]
name = "chainofcommand"
version = "0.0.1"
authors = ["Berkus Decker <berkus+vesper@metta.systems>"]
description = "Host server for chainboot"
license = "BlueOak-1.0.0"
categories = ["no-std", "embedded", "os"]
publish = false
edition = "2021"

[badges]
maintenance = { status = "experimental" }

[dependencies]
clap = "3.0"
seahash = "4.1"
anyhow = "1.0"
fehler = "1.0"
crossterm = { version = "0.22", features = ["event-stream"] }
tokio-serial = "5.4"
tokio = { version = "1.15", features = ["full"] }
futures = "0.3"
defer = "0.1"
tokio-util = { version = "0.6", features = ["codec"] }
bytes = "1.1"
