#
# SPDX-License-Identifier: BlueOak-1.0.0
#
# Copyright (c) Berkus Decker <berkus+vesper@metta.systems>
#
# Build chainofcommand tool
#
[tasks.build]
clear = true
alias = "build-coc"

[tasks.build-device]
clear = true
alias = "empty"

[tasks.build-coc]
command = "cargo"
args = ["build"]

[tasks.chainofcommand]
alias = "build-coc"

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.xtool-clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]
