#
# SPDX-License-Identifier: BlueOak-1.0.0
#
# Copyright (c) Berkus Decker <berkus+vesper@metta.systems>
#
# Build chainofcommand tool
#
[tasks.build]
command = "cargo"
args = ["build"]

[tasks.chainofcommand]
alias = "build"

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]
