#
# SPDX-License-Identifier: BlueOak-1.0.0
#
# Copyright (c) Berkus Decker <berkus+vesper@metta.systems>
#
# Build chainofcommand tool
#
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
alias = "build-coc"

[tasks.build-device]
alias = "empty"

[tasks.build-coc]
workspace = false
command = "cargo"
args = ["build"]

[tasks.chainofcommand]
workspace = false
alias = "build-coc"

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.xtool-clippy] # todo this should be modules-specific? or just "clippy" for workspace cmd
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]
