#
# SPDX-License-Identifier: BlueOak-1.0.0
#
# Copyright (c) Berkus Decker <berkus+vesper@metta.systems>
#
# Build nucleus library (machine)
#
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clippy]
workspace = false
dependencies = ["xtool-clippy"]

# FIXME: we should not have to spell this out here
[tasks.zellij-nucleus]
disabled = true
