[package]
name = "libconsole"

description = "Console functions."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[features]
default = []
qemu = []

[dependencies]
aarch64-cpu = { workspace = true }
liblocking = { workspace = true }
liblog = { workspace = true }
libqemu = { workspace = true }
libtime = { workspace = true }

[lib]
test = false

[lints]
workspace = true
