[package]
name = "vesper-exceptions"

description = "Vesper nanokernel CPU exceptions handling."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

publish = false

[badges]
maintenance = { status = "experimental" }

[features]
default = []
qemu = []
test_build = []

[dependencies]
aarch64-cpu = { workspace = true }
liblocal-irq = { workspace = true }
liblog = { workspace = true }
tock-registers = { workspace = true }

# Tests are offloaded to kernel integration tests binary.
[lib]
test = false
harness = false

[lints]
workspace = true
