[package]
name = "libmachine"

description = "Vesper nanokernel shared code library, useful also for the chainboot loader."

authors = { workspace = true }
categories = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[badges]
maintenance = { status = "experimental" }

[features]
default = []
# Enable JTAG debugging of kernel - enable jtag helpers and
# block waiting for JTAG probe attach at the start of kernel main.
jtag = []
# Build for running under QEMU with semihosting, so various halt/reboot options would for example quit QEMU instead.
qemu = []

[dependencies]
libcpu = { workspace = true }
libexception = { workspace = true }
liblocal-irq = { workspace = true }
liblog = { workspace = true }
libqemu = { workspace = true }

[lib]
test = false

[lints]
workspace = true
